set_property PACKAGE_PIN T20 [get_ports ad9122_freme_p]
set_property PACKAGE_PIN N20 [get_ports ad9122_fpga_clk_p]


set_property PACKAGE_PIN T14 [get_ports ad9122_dci_p]
set_property PACKAGE_PIN V20 [get_ports {AD9122_data_p[15]}]
set_property PACKAGE_PIN N18 [get_ports {AD9122_data_p[14]}]
set_property PACKAGE_PIN P15 [get_ports {AD9122_data_p[13]}]
set_property PACKAGE_PIN Y18 [get_ports {AD9122_data_p[12]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[15]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[14]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[13]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[12]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[11]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[10]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[9]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[8]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[7]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[6]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[5]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[4]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[3]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[2]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[1]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {AD9122_data_p[0]}]
set_property PACKAGE_PIN V17 [get_ports {AD9122_data_p[11]}]
set_property PACKAGE_PIN T17 [get_ports {AD9122_data_p[10]}]
set_property PACKAGE_PIN Y16 [get_ports {AD9122_data_p[9]}]
set_property PACKAGE_PIN T16 [get_ports {AD9122_data_p[8]}]
set_property PACKAGE_PIN V15 [get_ports {AD9122_data_p[7]}]
set_property PACKAGE_PIN W14 [get_ports {AD9122_data_p[6]}]
set_property PACKAGE_PIN U14 [get_ports {AD9122_data_p[5]}]
set_property PACKAGE_PIN U13 [get_ports {AD9122_data_p[4]}]
set_property PACKAGE_PIN V12 [get_ports {AD9122_data_p[3]}]
set_property PACKAGE_PIN P14 [get_ports {AD9122_data_p[2]}]
set_property PACKAGE_PIN T12 [get_ports {AD9122_data_p[1]}]
set_property PACKAGE_PIN T11 [get_ports {AD9122_data_p[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[0]}]
set_property PACKAGE_PIN K18 [get_ports {dac_data[0]}]
set_property PACKAGE_PIN K17 [get_ports {dac_data[1]}]
set_property PACKAGE_PIN D18 [get_ports {dac_data[2]}]
set_property PACKAGE_PIN E17 [get_ports {dac_data[3]}]
set_property PACKAGE_PIN B19 [get_ports {dac_data[4]}]
set_property PACKAGE_PIN A20 [get_ports {dac_data[5]}]
set_property PACKAGE_PIN H17 [get_ports {dac_data[6]}]
set_property PACKAGE_PIN H16 [get_ports {dac_data[7]}]
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
#create_clock -period 20.000 -name clk_50M [get_ports clk_50M]


set_property PACKAGE_PIN U18 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS18 [get_ports sys_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property PACKAGE_PIN N15 [get_ports uart_txd]
set_property PACKAGE_PIN N16 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

set_property IOSTANDARD LVCMOS33 [get_ports pwm_port]
set_property PACKAGE_PIN G15 [get_ports pwm_port]

set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports ad9122_dci_p]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports ad9122_dci_n]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports ad9122_fpga_clk_p]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports ad9122_fpga_clk_n]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports ad9122_freme_p]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports ad9122_freme_n]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports ad9516_clk_p]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports ad9516_clk_n]
set_property IOSTANDARD LVCMOS33 [get_ports lt3471_enn]
set_property PACKAGE_PIN R16 [get_ports pwm_diff_port_p]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports pwm_diff_port_p]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports pwm_diff_port_n]
set_property PACKAGE_PIN H20 [get_ports ad9748_cken]
set_property IOSTANDARD LVCMOS33 [get_ports ad9748_cken]
set_property PACKAGE_PIN U8 [get_ports ad9748_sleep]
set_property IOSTANDARD LVCMOS33 [get_ports ad9748_sleep]
set_property PACKAGE_PIN U7 [get_ports ad9516_status]
set_property IOSTANDARD LVCMOS33 [get_ports ad9516_status]
set_property PACKAGE_PIN U5 [get_ports ad9516_lock_detect]
set_property PACKAGE_PIN T5 [get_ports ad9516_refmon]
set_property IOSTANDARD LVCMOS33 [get_ports ad9516_refmon]
set_property IOSTANDARD LVCMOS33 [get_ports ad9516_lock_detect]
set_property PACKAGE_PIN Y6 [get_ports ad9516_powerdown]
set_property IOSTANDARD LVCMOS33 [get_ports ad9516_powerdown]
set_property PACKAGE_PIN W10 [get_ports ad9516_irq]
set_property IOSTANDARD LVCMOS33 [get_ports ad9516_irq]
set_property PACKAGE_PIN Y11 [get_ports ad9122_spi_sdio]
set_property IOSTANDARD LVCMOS33 [get_ports ad9122_spi_sdio]
set_property PACKAGE_PIN Y13 [get_ports ad9122_spi_sclk]
set_property PACKAGE_PIN Y12 [get_ports ad9122_spi_csn]
set_property IOSTANDARD LVCMOS33 [get_ports ad9122_spi_csn]
set_property IOSTANDARD LVCMOS33 [get_ports ad9122_spi_sclk]
set_property PACKAGE_PIN W11 [get_ports ad9122_spi_sdo]
set_property IOSTANDARD LVCMOS33 [get_ports ad9122_spi_sdo]
set_property PACKAGE_PIN Y8 [get_ports ad9156_spi_sdio]
set_property IOSTANDARD LVCMOS33 [get_ports ad9156_spi_sdio]
set_property PACKAGE_PIN Y9 [get_ports ad9156_spi_csn]
set_property PACKAGE_PIN W9 [get_ports ad9156_spi_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports ad9156_spi_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports ad9156_spi_csn]
set_property IOSTANDARD LVCMOS33 [get_ports ad9156_spi_sdo]
set_property PACKAGE_PIN Y7 [get_ports ad9156_spi_sdo]
set_property PACKAGE_PIN W18 [get_ports ad9516_clk_p]

# set_property PACKAGE_PIN H15 [get_ports sys_rst]
# set_property IOSTANDARD LVCMOS33 [get_ports sys_rst]

# set_property PACKAGE_PIN V5 [get_ports sys_rst_n]

set_property PACKAGE_PIN J16 [get_ports led_breath]
set_property IOSTANDARD LVCMOS33 [get_ports led_breath]

set_property PACKAGE_PIN H15 [get_ports pwm_slow_port]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_50M]
